### ISSUE TITLE
dateformfield没有jsxdiabled

### ISSUE THREAD

**Issue by fengsx** [uxcore/uxcore-date-form-field#10]
目前 dateformfield的禁用状态是用 disabled 的，希望能够跟其他的formfield一样，加一个alias，叫jsxdisabled

**Comment by eternalsky** [comment]
我们未来的方向是去掉 jsx，可以提个 issue，让所有的 formfield 支持反过来的 disabled

**Comment by eternalsky** [comment]
https://github.com/uxcore/uxcore-form/issues/138
