### ISSUE TITLE
在dialog中，样式错乱

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-date-form-field#12]
图上传不上来了。。@光弘 发你了

**Comment by eternalsky** [comment]
跟在 Dialog 中没关系的吧，主要是撞到边界的原因。

**Comment by eternalsky** [comment]
fix in https://github.com/uxcore/uxcore-calendar/commit/e8b80a3d7f17fde2ed38300fee9ffbbf10516bd8
