### ISSUE TITLE
当jsxtype为cascade时希望部分属性可以支持传入数组，两个date分开控制

### ISSUE THREAD

**Issue by FE-Girl** [uxcore/uxcore-date-form-field#3]
例如 disabled、defauleValue、jsxfrom、jsxto 等

**Comment by eternalsky** [comment]
defaultValue 是不推荐使用的，form 都统一用 jsxvalues，jsxfrom 和 jsxto，没办法支持传入数组，因为前后时间是联动的，而且没有意义。

**Comment by eternalsky** [comment]
fix in ver. 0.4.1
