### ISSUE TITLE
非空校验出错

### ISSUE THREAD

**Issue by lpgray** [uxcore/uxcore-date-form-field#5]
自己编写了组件的 jsxRules，代码如下，发现此组件 `instantValidate` 必须为 true 才可以校验通过，假如不开启 `instantValidate`，第一次填写完数据清空以后就无法再次校验非空状态了。
```javascript
const jsxrules = [{
      validator: (value) => {
        if (typeof value === 'undefined') {
          return false;
        } else if (isArray(value) && value.length < 2) {
          return false;
        }
        for (let i = 0, l = value.length; i < l; i++) {
          if (!value[i]) {
            return false;
          }
        }
        return true;
      },
      errMsg: i18n('common.required')
    }];
```

第一步：页面渲染完成，时间段组件不填写，`Form.getValues()`，此时校验正常
第二步：填写 `DateFormField`，然后点击组件右上角叉叉清空，`Form.getValues()`校验错误，DateFormField我没填写，页面也不报错，jsxrules在上方代码中

**Comment by eternalsky** [comment]
第一次填写完数据清空以后就无法再次校验非空状态了。 
这一句请详细描述，数据如何清空的？ 无法再次校验，是永远校验通过，还是不经过校验，意义不明确。

==========

instantValidate 为 false，表明关闭了即时校验，那么校验是在何时进行？调用哪个 API，很多描述不清楚无法确定问题，能否提供 demo？

**Comment by lpgray** [comment]
已修改描述

**Comment by eternalsky** [comment]
outdated issue, reopen it if necessary
